--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/presentkim-pm/PersonaSkin
build-by-default: true
branches:
  - main
projects:
  PersonaSkin:
    icon: "icon.png"
    libs:
      - src: presentkim-pm/png-converter/png-converter
        version: ^1.1.0
...
